apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  version: 8.12.0
  count: 1
  elasticsearchRefs:
    - name: elastic-cluster
      clusterName: elastic-cluster
  podTemplate:
    spec:
      containers:
      - name: logstash
        env:
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-cluster-es-elastic-user
              key: elastic
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers
  pipelines:
  - pipeline.id: flask-logs
    config.string: |
      input {
        file {
          path => "/var/log/containers/*myapp*.log"
          start_position => "beginning"
          sincedb_path => "/dev/null"
          codec => "json"
        }
      }
      filter {
        mutate { add_field => { "app" => "flask-demo" } }
      }
      output {
        elasticsearch {
          hosts => ["https://elastic-cluster-es-http.default.svc:9200"]
          user => "elastic"
          password => "${ES_PASSWORD}"
          index => "flask-logs-%{+YYYY.MM.dd}"
          ssl_certificate_verification => false
        }
        stdout { codec => rubydebug }
      }
